### PR TITLE
db: Add Sonos remote

### PR DESCRIPTION
**Pull request by Slion**
Patch HDfury remote types.

### CODE REVIEW

**Comment by Biswa96** [comment]
Would you like to split the changes into different commit or can I do that? Also, the sonos remote can be written in button files.

**Comment by Slion** [comment]
> Would you like to split the changes into different commit or can I do that?

You can do that if you want. If you think there is any value in doing so.

> Also, the sonos remote can be written in button files.

It could, but it's easier like that. Just one file instead of four 😁

**Comment by Biswa96** [comment]
ok, I shall split the changes.

BTW, should the directory name be changed from "Sonos" to something like "`Sonos <device name here>`" ? We could have different devices in future. Sonos has many audio related devices.

**Comment by Slion** [comment]
Thought about that, if they ever make a new set of IR code we could still rename them. However this is highly unlikely, they are really not big on IR, they do IP instead. For the past teen years they've only had that one set with four codes and I don't think they will ever be changing that. All their soundbars use the same codes. Play bar, Play base, Beam and Arc.

**Comment by Biswa96** [comment]
The changes are added in 6202e146d0cd7a71b1432c6d56dfa5f6b9e34382 and e92dacac2b4069364033153ba0f1f88222744b95

**Pull request closed without merging**
